---
name: "Terraform"

on: [push, pull_request]

jobs:
  format_check:
    name: "terraform fmt check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform fmt -check
