---
name: "Terraform"

on: [push, pull_request]

jobs:
  format_check:
    name: "terraform fmt check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform fmt -check

  init:
    name: "terraform fmt check"
    runs-on: ubuntu-latest
    needs: format_check
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init

  validate:
    name: "terraform fmt check"
    runs-on: ubuntu-latest
    needs: init
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform validate

  plan:
    name: "terraform plan"
    runs-on: ubuntu-latest
    needs: [init, validate]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform plan -no-color